# orion_core/brain/coder_runner.py

"""
CoderRunner — Orion's Background Coding Task Executor
-----------------------------------------------------

This component provides a safe, async, serial execution environment
for long coding tasks generated by Thinker v2.

Key Features:
- Serial task queue (no parallel VRAM contention)
- Pause / Resume / Stop task
- Dynamic coder model loading (DeepSeek-Coder-6.7b)
- Task checkpoints (resume later)
- Status reporting through Brain bubble_thought()
- Writes files safely (no destructive overwrite unless approved)

Used by Brain:
    await coder_runner.start_task(task_id, instructions)
    await coder_runner.pause_task(task_id)
    await coder_runner.resume_task(task_id)
    await coder_runner.stop_task(task_id)
"""

import asyncio
import json
import os
import time
from typing import Optional, Dict, Any

from orion_core.brain.llm.coder_engine import get_coder_engine
from orion_core.brain.meta_bridge import MetaBridge


class CoderTaskState:
    IDLE = "idle"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"
    COMPLETED = "completed"
    ERROR = "error"


class CoderRunner:
    def __init__(self, bubble_thought=None):
        self.bubble = bubble_thought  # callback from Brain
        self.engine = get_coder_engine()
        self.bridge = MetaBridge()

        self.current_task_id: Optional[str] = None
        self.current_task_instructions: Optional[str] = None
        self.current_state = CoderTaskState.IDLE

        self._task_lock = asyncio.Lock()
        self._pause_event = asyncio.Event()
        self._pause_event.set()  # not paused initially

        self._stop_flag = False
        self.checkpoint_dir = "logs/coder_checkpoints"
        os.makedirs(self.checkpoint_dir, exist_ok=True)

    # -------------------------------------------------------------
    # USER-FACING OPERATIONS (CALLED BY BRAIN)
    # -------------------------------------------------------------
    async def start_task(self, task_id: str, instructions: str):
        """
        Begin a NEW coding task. If another task is active, stop it first.
        """
        async with self._task_lock:
            if self.current_state in (CoderTaskState.RUNNING, CoderTaskState.PAUSED):
                await self.stop_task(self.current_task_id)

            self.current_task_id = task_id
            self.current_task_instructions = instructions
            self.current_state = CoderTaskState.RUNNING
            self._stop_flag = False
            self._pause_event.set()

            if self.bubble:
                await self.bubble(f"Starting coding task '{task_id}'…")

            asyncio.create_task(self._run_task_loop())

    async def pause_task(self, task_id: str):
        """Pause the current task."""
        if task_id != self.current_task_id:
            return "No such active task."

        self.current_state = CoderTaskState.PAUSED
        self._pause_event.clear()

        if self.bubble:
            await self.bubble(f"Pausing task '{task_id}'.")

        return "Paused."

    async def resume_task(self, task_id: str):
        """Resume a paused task."""
        if task_id != self.current_task_id:
            return "No such active task."

        self.current_state = CoderTaskState.RUNNING
        self._pause_event.set()

        if self.bubble:
            await self.bubble(f"Resuming task '{task_id}'…")

        return "Resumed."

    async def stop_task(self, task_id: str):
        """Stop a running/paused task immediately."""
        if task_id != self.current_task_id:
            return "No such task."

        self._stop_flag = True
        self._pause_event.set()

        if self.bubble:
            await self.bubble(f"Stopping task '{task_id}'…")

        self.current_state = CoderTaskState.STOPPED
        return "Stopped."

    async def status(self) -> Dict[str, Any]:
        """Return full coder status for Thinker/Brain."""
        return {
            "task_id": self.current_task_id,
            "state": self.current_state,
        }

    # -------------------------------------------------------------
    # INTERNAL TASK LOOP
    # -------------------------------------------------------------
    async def _run_task_loop(self):
        """
        Executes instructions until:
            - task completes
            - paused
            - stopped
        """
        task_id = self.current_task_id
        instructions = self.current_task_instructions

        # Load checkpoint if exists:
        checkpoint = self._load_checkpoint(task_id)
        if checkpoint:
            instructions = checkpoint.get("remaining", instructions)
            if self.bubble:
                await self.bubble(f"Resuming '{task_id}' from checkpoint…")

        # Main execution loop:
        try:
            while not self._stop_flag:
                await self._pause_event.wait()  # wait if paused

                if self.current_state == CoderTaskState.PAUSED:
                    await asyncio.sleep(0.3)
                    continue

                # -------------------------------------------------
                # Generate code chunk
                # -------------------------------------------------
                with open("orion_core/brain/prompts/coder_system.txt", "r", encoding="utf-8") as f:
                    system_prompt = f.read()

                chunk = await self.engine.generate_code(
                    instructions,
                    system_prompt=system_prompt,
                    max_new_tokens=700,
                )

                # Save output
                out_path = self._write_chunk(task_id, chunk)

                if self.bubble:
                    await self.bubble(f"Task '{task_id}': generated output → {out_path}")

                # Mark completed
                self.current_state = CoderTaskState.COMPLETED
                self._delete_checkpoint(task_id)

                await self.engine.unload()

                if self.bubble:
                    await self.bubble(f"Task '{task_id}' completed.")

                return

        except Exception as e:
            self.current_state = CoderTaskState.ERROR
            await self.engine.unload()
            if self.bubble:
                await self.bubble(f"Coder error in task '{task_id}': {e}")
            return

    # -------------------------------------------------------------
    # CHECKPOINT HANDLING
    # -------------------------------------------------------------
    def _checkpoint_path(self, task_id: str) -> str:
        return os.path.join(self.checkpoint_dir, f"{task_id}.json")

    def _save_checkpoint(self, task_id: str, remaining: str):
        path = self._checkpoint_path(task_id)
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"remaining": remaining}, f,
                      ensure_ascii=False, indent=2)

    def _load_checkpoint(self, task_id: str) -> Optional[Dict[str, Any]]:
        path = self._checkpoint_path(task_id)
        if not os.path.exists(path):
            return None
        try:
            return json.loads(open(path, encoding="utf-8").read())
        except Exception:
            return None

    def _delete_checkpoint(self, task_id: str):
        path = self._checkpoint_path(task_id)
        if os.path.exists(path):
            os.remove(path)

    # -------------------------------------------------------------
    # FILE WRITING
    # -------------------------------------------------------------
    def _write_chunk(self, task_id: str, chunk: str) -> str:
        """
        Save coder output to file(s).
        If multi-file markers are present, write each file accordingly.
        """
        files = self._split_multi_file_output(chunk)

        written_paths: list[str] = []
        for rel_path, content in files.items():
            # Legacy: single file named by task
            if rel_path == "generated.txt":
                safe_name = task_id.replace(" ", "_")
                rel_path = f"generated_{safe_name}.txt"

            out_path = os.path.abspath(rel_path)
            os.makedirs(os.path.dirname(out_path), exist_ok=True)

            with open(out_path, "w", encoding="utf-8") as f:
                f.write(content)

            written_paths.append(out_path)

        # For bubble_thought, return just the first path
        return written_paths[0] if written_paths else ""

    # -------------------------------------------------------------

        # -------------------------------------------------------------
    # MULTI-FILE PARSER
    # -------------------------------------------------------------
    def _split_multi_file_output(self, raw: str) -> dict[str, str]:
        """
        Parse coder output into a {path: content} dict.

        Expected format:

        =====FILE: path/to/file.py=====
        <content>

        =====FILE: other/file.txt=====
        <content>
        """
        files: dict[str, str] = {}
        if "=====FILE:" not in raw:
            # Single anonymous blob, keep legacy behavior
            files["generated.txt"] = raw
            return files

        chunks = raw.split("=====FILE:")
        for chunk in chunks:
            chunk = chunk.strip()
            if not chunk:
                continue
            try:
                header, body = chunk.split("=====", 1)
            except ValueError:
                # Malformed, skip
                continue
            path = header.strip()
            content = body.lstrip("\n")
            files[path] = content
        return files
